### ISSUE TITLE
Basic Setup Explanation/help

### ISSUE THREAD

**Issue by Mart4672** [aditya00j/simulink_mavlink#2]
I'm so happy that this library was created as I think it should help with what I need. However, I'm still confused about how to get everything set up and working even after reading the documentation. 

![20190731_232802](https://user-images.githubusercontent.com/53550558/62265765-00959400-b3eb-11e9-854d-31f2bcc1b105.jpg)

I'm trying to get a Pixhawk controller that I'm programming w/ Simulink (which will be in the air) to send telemetry updates (just basic yaw, pitch, roll, vel, etc) via radio to the ground. I'm also unsure how many separate Simulink files need to be made and which components should be plugged into where for testing.

Any help would be appreciated.

**Comment by aditya00j** [comment]
Hi,
Sorry, I haven't been active on the PX4 programming in the past year. I hope you found the help you needed!
